### DISCUSSION TITLE
Proposal: Conventions for extra field data when creating Morio client modules

### DISCUSSION THREAD

**Discussion by joostdecock** [certeu/moriohub#2] [Ideas]
I feel it would be good to get on the same page about what kind of data to (always) add when collecting data via the Morio client.

This is a proposal, please do not hesitate to share your comments.

### @timestamp 

While Beats will auto-generate a timestamp, we should strive to always populate this field with the actual timestamp if that is available. For example, if a log line has a timestamp in it, that value should be used.

See [this comment](https://github.com/certeu/morio-templates/discussions/2#discussioncomment-11449339) by @serge-tellene for tips on how to do that.

### host.id

The `host.id` must always hold the Morio client UUID. 

To add it, use the template feature. For example, here is a processor that does this:

```yaml
  - add_fields:
      target: host
      fields:
        id: {{ MORIO_CLIENT_UUID }}
```

### morio.module

The `morio.module` name always holds the Morio module name.
To add it, use the template feature. For example, here is a processor that does this:

```yaml
  - add_fields:
      target: morio
      fields:
        module: {{ MORIO_MODULE_NAME }}
```

## Optional fields

These are conventions for overloading events with extra info. You can add all the extra info you want, but it's good to have consensus on some common use cases, like the ones below:

### splunk.index

If you want to indicate when index should be used when later ingesting the data into Splunk, please use the `splunk.index` field for this.

Here is an example procesor that does this:

```yaml
  - add_fields:
      target: splunk
      fields:
        index: index-name-here
```

**Comment by serge-tellene** [comment]
I agree. Is the syntax not slightly different (with spaces before `target` and `fields`)?
I'd summarise the above:

```
    - add_fields:
        target: morio
        fields:
          module: {{ MORIO_MODULE_NAME }}

    - add_fields:
        target: host
        fields:
          id: {{ MORIO_CLIENT_UUID }}
```

Also, we could agree that the timestamp of the event (if present in the event) should be mapped to the top-level `@timestamp` field. This can be achieved using the _timestamp_ processor with a layout matching the syntax of the logs. Supposing that we have extracted the timestamp into `temp_timestamp` (with a _dissect_ processor, for instance):

```
    - timestamp:
        field: temp_timestamp
        layouts:
          - '02/Jan/2006:15:04:05 -0700'
          
    - drop_fields:
        fields: [temp_timestamp]
```
